/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme.putnik;

import domen.Putnik;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontroler.Komunikacija;
import modeli.ModelTabelePutnik;

/**
 *
 * @author Korisnik
 */
public class FrmSviPutnici extends javax.swing.JDialog {

    private java.awt.Frame parent;
    /**
     * Creates new form FrmSviPutnici
     */
    public FrmSviPutnici(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.parent = parent;
        //tblPutnici.setModel(new ModelTabelePutnik());
        popuniTabelu();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPretraga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPutnici = new javax.swing.JTable();
        btnIzmeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnDetalji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Svi putnici", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setText("Pretraga:");

        txtPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPretragaActionPerformed(evt);
            }
        });

        tblPutnici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPutnici);

        btnIzmeni.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnIzmeni.setText("Izmeni");
        btnIzmeni.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnObrisi.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnObrisi.setText("Obrisi");
        btnObrisi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnDetalji.setText("Detalji");
        btnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnIzmeni, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(btnObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(btnDetalji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPretragaActionPerformed
        try {
            Putnik putnik = new Putnik();
            putnik.setIme(txtPretraga.getText());
            putnik.setPrezime(txtPretraga.getText());
            putnik.setBrojPasosa(txtPretraga.getText());
            putnik.setEmail(txtPretraga.getText());
            putnik.setTelefon(txtPretraga.getText());
            
            ArrayList<Putnik> lista = Komunikacija.getInstance().ucitajListuPutnika(putnik);
            ModelTabelePutnik model = new ModelTabelePutnik();
            model.setPutnici(lista);
            tblPutnici.setModel(model);
            
            //prepareView();
            
            if(model.getRowCount() == 0){
                JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje putnike po zadatoj vrednosti");
            }else{
                JOptionPane.showMessageDialog(this, "Sistem je nasao putnike po zadatoj vrednosti");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje putnike po zadatoj vrednosti");
            Logger.getLogger(FrmSviPutnici.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_txtPretragaActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        ModelTabelePutnik model = (ModelTabelePutnik) tblPutnici.getModel();
        int i = tblPutnici.getSelectedRow();
        
        if(i >= 0) {
            Putnik p = model.vratiPutnika(i);
            
            try {
                p = Komunikacija.getInstance().ucitajPutnika(p);
                
                JOptionPane.showMessageDialog(this, "Sistem je ucitao putnika");
                FrmNoviPutnik fnp = new FrmNoviPutnik(this.parent, true);
                fnp.setPutnik(p);
                fnp.setVisible(true);
                
                prepareView();
                popuniTabelu();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita putnika");
                Logger.getLogger(FrmSviPutnici.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }else{
            JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita putnika");
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed
    
    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        ModelTabelePutnik model = (ModelTabelePutnik) tblPutnici.getModel();
        int i = tblPutnici.getSelectedRow();
        
        if(i >= 0) {
            Putnik p = model.vratiPutnika(i);
            
            try {
                p = Komunikacija.getInstance().ucitajPutnika(p);
                
                JOptionPane.showMessageDialog(this, "Sistem je ucitao putnika");
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita putnika");
                Logger.getLogger(FrmSviPutnici.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            try {
                Komunikacija.getInstance().obrisiPutnika(p);
                model.obrisiPutnika(i);
                prepareView();
                JOptionPane.showMessageDialog(this, "Sistem je uspesno izbrisao putnika");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da izbrise putnika");
                Logger.getLogger(FrmSviPutnici.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else{
            JOptionPane.showMessageDialog(this, "Sistem ne moze da izbrise putnika");
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed
        ModelTabelePutnik model = (ModelTabelePutnik) tblPutnici.getModel();
        int i = tblPutnici.getSelectedRow();
        
        if(i >= 0) {
            Putnik p = model.vratiPutnika(i);
            
            try {
                p = Komunikacija.getInstance().ucitajPutnika(p);
        JOptionPane.showMessageDialog(this, "Sistem je ucitao putnika");
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita putnika");
                Logger.getLogger(FrmSviPutnici.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        
        FrmDetaljiPutnika fdp = new FrmDetaljiPutnika(parent, true);
        fdp.setPutnik(p);
        fdp.setVisible(true);}
    }//GEN-LAST:event_btnDetaljiActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPutnici;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables

    private void popuniTabelu() {
        try {
            ArrayList<Putnik> lista = Komunikacija.getInstance().ucitajListuPutnika();
            tblPutnici.setModel(new ModelTabelePutnik(lista));
        } catch (Exception ex) {
            Logger.getLogger(FrmSviPutnici.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
    }

    private void prepareView() {
        ModelTabelePutnik model = (ModelTabelePutnik) tblPutnici.getModel();
        boolean isEmpty = model.getRowCount() == 0;
        btnIzmeni.setEnabled(!isEmpty);
        btnObrisi.setEnabled(!isEmpty);
    }
}
