/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.TuristickiAgent;
import forme.putnik.FrmNoviPutnik;
import forme.putnik.FrmSviPutnici;
import forme.putovanje.FrmNovoPutovanje;
import forme.putovanje.FrmSvaPutovanja;
import forme.rezervacija.FrmNovaRezervacija;
import forme.rezervacija.FrmSveRezervacije;

/**
 *
 * @author Korisnik
 */
public class GlavnaForma extends javax.swing.JFrame {

    TuristickiAgent ulogovan;
    
    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma(TuristickiAgent ta) {
        initComponents();
        setLocationRelativeTo(null);
        this.ulogovan = ta;
        txtUlogovan.setText(ulogovan.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        txtUlogovan = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jPutnik = new javax.swing.JMenu();
        jMenuItemDodajPutnika = new javax.swing.JMenuItem();
        jMenuItemManipulacijaPutnicima = new javax.swing.JMenuItem();
        jPutovanje = new javax.swing.JMenu();
        jMenuItemDodajPutovanje = new javax.swing.JMenuItem();
        jMenuItemManipulacijaPutovanja = new javax.swing.JMenuItem();
        jRezervacija = new javax.swing.JMenu();
        jMenuItemDodajRezervaciju = new javax.swing.JMenuItem();
        jMenuItemManipulacijaRezervacijama = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setText("Trenutno ulogovan turisticki agent:");

        txtUlogovan.setEditable(false);
        txtUlogovan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUlogovanActionPerformed(evt);
            }
        });

        jMenuBar1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, java.awt.SystemColor.activeCaption));

        jPutnik.setText("Putnik");

        jMenuItemDodajPutnika.setText("Dodaj putnika");
        jMenuItemDodajPutnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajPutnikaActionPerformed(evt);
            }
        });
        jPutnik.add(jMenuItemDodajPutnika);

        jMenuItemManipulacijaPutnicima.setText("Manipulacija putnicima");
        jMenuItemManipulacijaPutnicima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManipulacijaPutnicimaActionPerformed(evt);
            }
        });
        jPutnik.add(jMenuItemManipulacijaPutnicima);

        jMenuBar1.add(jPutnik);

        jPutovanje.setText("Putovanje");

        jMenuItemDodajPutovanje.setText("Dodaj putovanje");
        jMenuItemDodajPutovanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajPutovanjeActionPerformed(evt);
            }
        });
        jPutovanje.add(jMenuItemDodajPutovanje);

        jMenuItemManipulacijaPutovanja.setText("Manipulacija putovanja");
        jMenuItemManipulacijaPutovanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManipulacijaPutovanjaActionPerformed(evt);
            }
        });
        jPutovanje.add(jMenuItemManipulacijaPutovanja);

        jMenuBar1.add(jPutovanje);

        jRezervacija.setText("Rezervacija");

        jMenuItemDodajRezervaciju.setText("Dodaj rezervaciju");
        jMenuItemDodajRezervaciju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajRezervacijuActionPerformed(evt);
            }
        });
        jRezervacija.add(jMenuItemDodajRezervaciju);

        jMenuItemManipulacijaRezervacijama.setText("Manipulacija rezervacijama");
        jMenuItemManipulacijaRezervacijama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManipulacijaRezervacijamaActionPerformed(evt);
            }
        });
        jRezervacija.add(jMenuItemManipulacijaRezervacijama);

        jMenuBar1.add(jRezervacija);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtUlogovan, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUlogovan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemDodajPutnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajPutnikaActionPerformed
        FrmNoviPutnik frmNoviPutnik = new FrmNoviPutnik(this, true);
        frmNoviPutnik.setVisible(true);
    }//GEN-LAST:event_jMenuItemDodajPutnikaActionPerformed

    private void jMenuItemManipulacijaPutnicimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManipulacijaPutnicimaActionPerformed
        FrmSviPutnici frmSviPutnici = new FrmSviPutnici(this, true);
        frmSviPutnici.setVisible(true);
    }//GEN-LAST:event_jMenuItemManipulacijaPutnicimaActionPerformed

    private void jMenuItemDodajPutovanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajPutovanjeActionPerformed
        FrmNovoPutovanje frmNovoPutovanje = new FrmNovoPutovanje(this, true);
        frmNovoPutovanje.setVisible(true);
    }//GEN-LAST:event_jMenuItemDodajPutovanjeActionPerformed

    private void jMenuItemManipulacijaPutovanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManipulacijaPutovanjaActionPerformed
        FrmSvaPutovanja frmSvaPutovanja = new FrmSvaPutovanja(this, true);
        frmSvaPutovanja.setVisible(true);
    }//GEN-LAST:event_jMenuItemManipulacijaPutovanjaActionPerformed

    private void jMenuItemDodajRezervacijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajRezervacijuActionPerformed
        FrmNovaRezervacija frmNovaRezervacija = new FrmNovaRezervacija(this, true, ulogovan);
        frmNovaRezervacija.setVisible(true);
    }//GEN-LAST:event_jMenuItemDodajRezervacijuActionPerformed

    private void jMenuItemManipulacijaRezervacijamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManipulacijaRezervacijamaActionPerformed
        FrmSveRezervacije frmSveRezervacije = new FrmSveRezervacije(this, true, ulogovan);
        frmSveRezervacije.setVisible(true);
    }//GEN-LAST:event_jMenuItemManipulacijaRezervacijamaActionPerformed

    private void txtUlogovanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUlogovanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUlogovanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemDodajPutnika;
    private javax.swing.JMenuItem jMenuItemDodajPutovanje;
    private javax.swing.JMenuItem jMenuItemDodajRezervaciju;
    private javax.swing.JMenuItem jMenuItemManipulacijaPutnicima;
    private javax.swing.JMenuItem jMenuItemManipulacijaPutovanja;
    private javax.swing.JMenuItem jMenuItemManipulacijaRezervacijama;
    private javax.swing.JMenu jPutnik;
    private javax.swing.JMenu jPutovanje;
    private javax.swing.JMenu jRezervacija;
    private javax.swing.JTextField txtUlogovan;
    // End of variables declaration//GEN-END:variables


}
